name: Build Docker Container & Push to DO Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_django:
    uses: msvajgl/Django-Kubernetes/.github/workflows/test-django.yaml@main
  docker_build:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: test-key-not-good
    steps:
    - uses: actions/checkout@v2